server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: word-ai-app
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/word_ai}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  ai:
    openai:
      api-key: ${GOOGLE_AI_API_KEY:placeholder-key}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          completions-path: /chat/completions
          model: gemini-2.5-pro

bootstrap:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}

validation:
  password:
    min-length: ${PASSWORD_MIN_LENGTH:4}
    max-length: ${PASSWORD_MAX_LENGTH:50}
    min-uppercase: ${PASSWORD_MIN_UPPERCASE:0}
    min-lowercase: ${PASSWORD_MIN_LOWERCASE:0}
    min-digit: ${PASSWORD_MIN_DIGIT:0}
    min-special: ${PASSWORD_MIN_SPECIAL:0}
    allow-whitespace: ${PASSWORD_ALLOW_WHITESPACE:false}

security:
  register-path: ${SECURITY_REGISTER_PATH:/api/v1/auth/register}
  jwt-secret: ${SECURITY_JWT_SECRET:secret}
  jwt-expiration-ms: ${SECURITY_JWT_EXPIRATION_MS:86400000}
  enabled: ${SECURITY_ENABLED:true}
  login-url: ${LOGIN_URL:/api/v1/auth/login}
  username-parameter: username
  password-parameter: password
  

logging:
  level:
    "[org.springframework.security]": DEBUG
    "[com.github.muhsenerdev]": TRACE

words:
  max-insertion: ${WORDS_MAX_INSERTION:20}

prompts:
  english-to-turkish: ${PROMPTS_ENGLISH_TO_TURKISH:english-turkish-1}
